# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

required = ["github.com/roboll/go-vendorinstall", "github.com/golang/protobuf/protoc-gen-go", "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway"]

[[constraint]]
  name = "github.com/CentrifugeInc/centrifuge-protobufs"
  source = "git@github.com:CentrifugeInc/centrifuge-protobufs"
  branch = "master"

[[constraint]]
  name = "github.com/Masterminds/semver"
  version = "1.4.2"

[[constraint]]
  name = "github.com/centrifuge/precise-proofs"
  source = "git@github.com:centrifuge/precise-proofs"
  branch = "master"

[[override]]
  revision = "fbb7cafc5ae411e13e718172f5af7917ad6c3ed7"
  name = "github.com/xsleonard/go-merkle"

[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  source = "git@github.com:ethereum/go-ethereum"

[[override]]
  name = "github.com/satori/go.uuid"
  revision = "36e9d2ebbde5e3f13ab2e25625fd453271d6522e"

[[constraint]]
  name = "github.com/go-errors/errors"
  version = "1.0.1"

[[override]]
  name = "github.com/rjeczalik/notify"
  version = "0.9.1"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"

[[constraint]]
  version="^1.4.1"
  name = "github.com/grpc-ecosystem/grpc-gateway"
  source = "git@github.com:grpc-ecosystem/grpc-gateway"

[[constraint]]
  name = "github.com/ipfs/go-cid"
  version = "0.7.21"

[[constraint]]
  name = "github.com/ipfs/go-datastore"
  revision = "f2426c09e56ae390fc416f21b224c7d7ad13418c"

[[constraint]]
  name = "github.com/ipfs/go-ipfs-addr"
  version = "0.1.13"

[[constraint]]
  name = "github.com/ipfs/go-log"
  version = "1.5.3"

[[override]]
  name = "github.com/libp2p/go-libp2p-metrics"
  revision  = "a3a76fa99809135a2421982ff2958a544aa517ee"

[[override]]
  name = "github.com/libp2p/go-flow-metrics"
  revision = "3b3bcfcf78f2dc0e85be13ef3c3adc64cc5a9347"

[[override]]
  name = "github.com/libp2p/go-libp2p-routing"
  revision = "559f55cc93672421b61e89e2c19d35e5bed761e9"

[[override]]
  name = "github.com/libp2p/go-tcp-transport"
  revision = "578cd65fcec1d08d226d1b186e4548065e6bd65c"

[[override]]
  name = "github.com/libp2p/go-libp2p-transport"
  revision = "7f67e6aa68aa4b679c21179d32ab08d77a149cef"

[[override]]
  name = "github.com/libp2p/go-ws-transport"
  revision = "0cf90461ccc19765a5afafa9c2f58291471f1f09"

[[override]]
  name = "github.com/libp2p/go-libp2p-conn"
  revision = "8058ec7c7d8d3834119a164005482ea696f028e4"

[[override]]
  name = "github.com/libp2p/go-libp2p-record"
  revision = "6774ecef51dde72303f21f45aa4bf72a3aed18d1"

[[override]]
  name = "github.com/libp2p/go-libp2p-secio"
  revision = "437de218ca1fc65dfbf7b2b084519665bbaf7781"

[[override]]
  name = "github.com/libp2p/go-libp2p-interface-pnet"
  revision = "adc9472a14d21a9da75b21a8fba6b97f18ec545e"

[[override]]
  name = "github.com/libp2p/go-libp2p-circuit"
  revision = "e85b2ba300206b73ffce804a1af20862ff1e12de"
[[override]]
name = "github.com/libp2p/go-libp2p-net"
revision = "64c31f18a9753193909544f1a606148894cbe878"

[[override]]
  name = "github.com/libp2p/go-libp2p-host"
  revision = "dfeeb00fc9decef43a6bc47b555a530cb38e0c62"
[[override]] 
  name = "github.com/libp2p/go-libp2p-interface-conn"
  revision = "0635e022759c738c55b7769cc6307506946089b9"
[[override]]
  name = "github.com/libp2p/go-libp2p-interface-connmgr"
  revision = "201197111979ad70393a51d80cb12c5dfcee9d01"



[[override]]
  name = "github.com/multiformats/go-multiaddr"
  revision = "123a717755e0559ec8fda308019cd24e0a37bb07"
[[override]]
  name = "github.com/multiformats/go-multiaddr-dns"
  revision = "b431cd0a670beb991d0d0dc3defd2b89125aa34e"
[[override]]
  name = "github.com/multiformats/go-multiaddr-net"
  revision = "6040dff26de27e20b248b08041fdb65e6ba45b58"
[[override]]
  name = "github.com/multiformats/go-multibase"
  revision = "dfd5076869faca5aed2886dcba60b44a0d0e9c01"
[[override]]
  name = "github.com/multiformats/go-multicodec-packed"
  revision = "9004b413b478e5a878e4a879358cce02e5df4995"
[[override]]
  name = "github.com/multiformats/go-multihash"
  revision = "468a1b73e980e5aff011d308623e43e28c582b16"
[[override]]
  name = "github.com/multiformats/go-multistream"
  revision = "1bc5dd803d20cf91d8ec905ac3580e3ea3c8c995"

[[override]]
  name = "github.com/libp2p/go-addr-util"
  revision = "a9d6b939b59796c4933f56a8e628d6682d8d2a05"

[[constraint]]
  name = "github.com/libp2p/go-libp2p"
  revision = "5180df872e5ef34074bc6977b78f6b6e98553788"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-crypto"
  revision = "f2afd8b3d4e358a6092159c813cb2bdf6d984e68"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-host"
  revision = "dfeeb00fc9decef43a6bc47b555a530cb38e0c62"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-kad-dht"
  revision = "911433bc89860f0286b5d61d993bb8ccaec000d4"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-peer"
  revision = "296ae64e3db4af20e64270faa18e28797643480e"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-peerstore"
  revision = "2c122745dcc9c03c80b0203ce89c445ace6aa596"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-swarm"
  revision = "881b974a81faf652c196bda4331300683f18b539" 

[[constraint]]
  name = "github.com/magiconair/properties"
  version = "1.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  name = "github.com/multiformats/go-multiaddr"
  version = "1.2.7"

[[constraint]]
  name = "github.com/multiformats/go-multihash"
  version = "1.0.8"

[[constraint]]
  branch = "master"
  name = "github.com/paralin/go-libp2p-grpc"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  branch = "master"
  name = "github.com/syndtr/goleveldb"

[[constraint]]
  branch = "master"
  name = "github.com/whyrusleeping/go-logging"

[[constraint]]
  branch = "master"
  name = "github.com/whyrusleeping/go-smux-multistream"

[[constraint]]
  branch = "master"
  name = "github.com/whyrusleeping/go-smux-yamux"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.13.0"

[[prune.project]]
    name = "github.com/ethereum/go-ethereum"
    non-go = false
    unused-packages = false

[[prune.project]]
    name = "github.com/CentrifugeInc/centrifuge-protobufs"
    non-go = false
    unused-packages = false

[[prune.project]]
    name = "github.com/grpc-ecosystem/grpc-gateway"
    non-go = false
    unused-packages = false

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "gopkg.in/resty.v1"
  version = "1.7.0"
