# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

required = ["github.com/centrifuge/centrifuge-ethereum-contracts", "github.com/roboll/go-vendorinstall", "github.com/golang/protobuf/protoc-gen-go", "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway", "golang.org/x/tools/cmd/goimports"]

[[constraint]]
  name = "github.com/centrifuge/centrifuge-protobufs"
  revision = "34ce7eaff0b89ac4a34e60654d34297747e5a7b4"

[[override]]
  name = "github.com/centrifuge/centrifuge-ethereum-contracts"
  revision = "d9a240d86d05350de86c26ed23d72b45562ae155"

[[constraint]]
  name = "github.com/Masterminds/semver"
  version = "1.4.2"

[[override]]
  name = "github.com/centrifuge/precise-proofs"
  revision = "8957bc48e1bd690a835c630fa6fdfd141c41f5dd"

[[constraint]]
  name = "github.com/centrifuge/gocelery"
  revision = "80f35a18b9a0c632d7843e7e536873b0536f0040"

[[override]]
  name = "github.com/xsleonard/go-merkle"
  revision = "fbb7cafc5ae411e13e718172f5af7917ad6c3ed7"

[[override]]
  name = "github.com/ethereum/go-ethereum"
  source = "github.com/centrifuge/go-ethereum"
  revision = "27e633ca943ee9f49614b9ea074667227402b571"

[[override]]
  name = "github.com/satori/go.uuid"
  revision = "36e9d2ebbde5e3f13ab2e25625fd453271d6522e"

[[constraint]]
  name = "github.com/go-errors/errors"
  version = "1.0.1"

[[override]]
  name = "github.com/rjeczalik/notify"
  version = "0.9.1"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.2.0"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version= "1.5.0"

[[constraint]]
  name = "github.com/ipfs/go-cid"
  revision = "5b04f3043387b02aeeee6a35899f0e767bae3b33"

[[constraint]]
  name = "github.com/ipfs/go-datastore"
  revision = "bd0caea1845f2ffebea4f3d20ec5b4b50a4c78c5"

[[constraint]]
  name = "github.com/ipfs/go-ipfs-addr"
  version = "0.1.22"

[[constraint]]
  name = "github.com/ipfs/go-log"
  version = "1.5.3"

[[override]]
  name = "github.com/libp2p/go-libp2p-metrics"
  version = "2.1.5"

[[override]]
  name = "github.com/libp2p/go-flow-metrics"
  version = "0.2.0"

[[override]]
  name = "github.com/libp2p/go-libp2p-routing"
  version = "2.4.10"

[[override]]
  name = "github.com/libp2p/go-tcp-transport"
  version = "2.0.9"

[[override]]
  name = "github.com/libp2p/go-libp2p-transport"
  version = "3.0.9"

[[override]]
  name = "github.com/libp2p/go-ws-transport"
  version = "2.0.9"

[[override]]
  name = "github.com/libp2p/go-libp2p-record"
  version = "4.1.6"

[[override]]
  name = "github.com/libp2p/go-libp2p-secio"
  version = "2.0.9"

[[override]]
  name = "github.com/libp2p/go-libp2p-interface-pnet"
  version = "3.0.0"

[[override]]
  name = "github.com/libp2p/go-libp2p-circuit"
  version = "2.2.1"

[[override]]
  name = "github.com/libp2p/go-libp2p-net"
  version = "3.0.9"

[[override]]
  name = "github.com/libp2p/go-libp2p-host"
  version = "3.0.9"

[[override]]
  name = "github.com/libp2p/go-libp2p-interface-connmgr"
  version = "0.0.15"

[[override]]
  name = "github.com/multiformats/go-multiaddr"
  version = "1.2.7"

[[override]]
  name = "github.com/multiformats/go-multiaddr-dns"
  version = "0.2.3"

[[override]]
  name = "github.com/multiformats/go-multiaddr-net"
  version = "1.6.2"

[[override]]
  name = "github.com/multiformats/go-multibase"
  version = "0.2.6"

[[override]]
  name = "github.com/multiformats/go-multihash"
  version = "1.0.8"

[[override]]
  name = "github.com/multiformats/go-multistream"
  version = "0.3.7"

[[override]]
  name = "github.com/libp2p/go-addr-util"
  version = "2.0.5"

[[constraint]]
  name = "github.com/libp2p/go-libp2p"
  version = "6.0.1"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-crypto"
  version = "2.0.1"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-host"
  version = "3.0.9"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-kad-dht"
  version = "4.3.9"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-peer"
  version = "2.3.7"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-peerstore"
  version = "1.5.0"

[[override]]
  name = "github.com/libp2p/go-libp2p-swarm"
  version = "3.0.11"

[[constraint]]
  name = "github.com/magiconair/properties"
  version = "1.8.0"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.0.0"

[[constraint]]
  name = "github.com/multiformats/go-multiaddr"
  version = "1.2.7"

[[constraint]]
  name = "github.com/multiformats/go-multihash"
  version = "1.0.8"

[[constraint]]
  name = "github.com/paralin/go-libp2p-grpc"
  source = "github.com/vedhavyas/go-libp2p-grpc"
  revision = "04711f07389ecbca09d7999474dda4a88c955c73"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.2.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "github.com/syndtr/goleveldb"
  revision = "ae2bd5eed72d46b28834ec3f60db3a3ebedd8dbd"

[[constraint]]
  name = "github.com/whyrusleeping/go-logging"
  revision = "0457bb6b88fc1973573aaf6b5145d8d3ae972390"

[[override]]
  name = "github.com/whyrusleeping/go-smux-multistream"
  version = "2.0.2"

[[override]]
  name = "github.com/whyrusleeping/go-smux-yamux"
  revision = "eac25f3e2d47aae211e457e7664b52634c95eea8"

[[constraint]]
  name = "golang.org/x/crypto"
  revision = "0e37d006457bf46f9e6692014ba72ef82c33022c"

[[constraint]]
  name = "golang.org/x/net"
  revision = "26e67e76b6c3f6ce91f7c52def5af501b4e0f3a2"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.15.0"

[[constraint]]
  name = "gopkg.in/resty.v1"
  version = "1.9.1"

[[override]]
  name = "google.golang.org/genproto"
  revision = "5a2fd4cab2d6d4a18e70c34937662526cd0c4bd1"

[[prune.project]]
    name = "github.com/libp2p/go-libp2p"
    unused-packages = false

[[prune.project]]
    name = "github.com/centrifuge/centrifuge-ethereum-contracts"
    unused-packages = false

[[prune.project]]
    name = "github.com/ethereum/go-ethereum"
    unused-packages = false

[[prune.project]]
    name = "github.com/centrifuge/centrifuge-protobufs"
    unused-packages = false

[[prune.project]]
    name = "github.com/grpc-ecosystem/grpc-gateway"
    unused-packages = false

[[prune.project]]
    name = "github.com/hashicorp/go-multierror"
    unused-packages = false

[prune]
  go-tests = true
  unused-packages = true