# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

required = ["github.com/centrifuge/centrifuge-ethereum-contracts", "github.com/roboll/go-vendorinstall", "golang.org/x/tools/cmd/goimports", "github.com/swaggo/swag", "github.com/urfave/cli"]

[[constraint]]
  name = "github.com/centrifuge/centrifuge-protobufs"
  source = "github.com/vedhavyas/centrifuge-protobufs"
  revision = "0e9dca6fe8ebd1067259a0680054207b4044a82e"

[[override]]
  name = "github.com/centrifuge/centrifuge-ethereum-contracts"
  revision = "863c5efc0a49aff1e9c1cf2ef5f72f62c65425ed"

[[constraint]]
  name = "github.com/Masterminds/semver"
  version = "1.4.2"

[[override]]
  name = "github.com/centrifuge/precise-proofs"
  revision = "f443fbe849de3fae72475c0838ec8eabf6930edd"

[[constraint]]
  name = "github.com/centrifuge/gocelery"
  revision = "98e4381dac54051f9a6cd6d4e0c2815d87f625d8"

[[override]]
  name = "github.com/ethereum/go-ethereum"
  revision = "d2328b604a2d4ecdccc47d8f9133593161cbd40a"

[[override]]
  name = "github.com/satori/go.uuid"
  revision = "36e9d2ebbde5e3f13ab2e25625fd453271d6522e"

[[constraint]]
  name = "github.com/go-errors/errors"
  version = "1.0.1"

[[override]]
  name = "github.com/rjeczalik/notify"
  version = "0.9.1"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.3.0"

[[constraint]]
  name = "golang.org/x/tools"
  revision = "677d2ff680c188ddb7dcd2bfa6bc7d3f2f2f75b2"

[[constraint]]
  name = "github.com/ipfs/go-cid"
  version = "0.0.1"

[[constraint]]
  name = "github.com/ipfs/go-datastore"
  revision = "bd0caea1845f2ffebea4f3d20ec5b4b50a4c78c5"

[[constraint]]
  name = "github.com/ipfs/go-ipfs-addr"
  version = "0.0.1"

[[constraint]]
  name = "github.com/ipfs/go-log"
  version = "0.0.1"

[[override]]
  name = "github.com/libp2p/go-libp2p-metrics"
  version = "0.0.1"

[[override]]
  name = "github.com/libp2p/go-flow-metrics"
  version = "0.0.1"

[[override]]
  name = "github.com/libp2p/go-libp2p-routing"
  version = "0.0.1"

[[override]]
  name = "github.com/libp2p/go-tcp-transport"
  version = "0.0.1"

[[override]]
  name = "github.com/libp2p/go-libp2p-transport"
  version = "0.0.4"

[[override]]
  name = "github.com/libp2p/go-ws-transport"
  version = "0.0.1"

[[override]]
  name = "github.com/libp2p/go-libp2p-record"
  version = "0.0.1"

[[override]]
  name = "github.com/libp2p/go-libp2p-secio"
  version = "0.0.1"

[[override]]
  name = "github.com/libp2p/go-libp2p-interface-pnet"
  version = "0.0.1"

[[override]]
  name = "github.com/libp2p/go-libp2p-circuit"
  version = "0.0.1"

[[override]]
  name = "github.com/libp2p/go-libp2p-net"
  version = "0.0.1"

[[override]]
  name = "github.com/libp2p/go-libp2p-host"
  version = "0.0.2"

[[override]]
  name = "github.com/libp2p/go-libp2p-interface-connmgr"
  version = "0.0.1"

[[override]]
  name = "github.com/multiformats/go-multiaddr"
  version = "0.0.2"

[[override]]
  name = "github.com/multiformats/go-multiaddr-dns"
  version = "0.0.2"

[[override]]
  name = "github.com/multiformats/go-multiaddr-net"
  version = "0.0.1"

[[override]]
  name = "github.com/multiformats/go-multibase"
  version = "0.0.1"

[[override]]
  name = "github.com/multiformats/go-multihash"
  version = "0.0.1"

[[override]]
  name = "github.com/multiformats/go-multistream"
  version = "0.0.1"

[[override]]
  name = "github.com/libp2p/go-addr-util"
  version = "0.0.1"

[[constraint]]
  name = "github.com/libp2p/go-libp2p"
  version = "0.0.3"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-crypto"
  version = "0.0.1"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-host"
  version = "0.0.2"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-kad-dht"
  version = "0.0.6"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-peer"
  version = "0.1.0"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-peerstore"
  version = "0.0.1"

[[override]]
  name = "github.com/libp2p/go-libp2p-swarm"
  version = "0.0.1"

[[constraint]]
  name = "github.com/magiconair/properties"
  version = "1.8.0"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.0.0"

[[constraint]]
  name = "github.com/multiformats/go-multiaddr"
  version = "0.0.2"

[[constraint]]
  name = "github.com/multiformats/go-multihash"
  version = "0.0.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.2.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[override]]
  name = "github.com/syndtr/goleveldb"
  revision = "ae2bd5eed72d46b28834ec3f60db3a3ebedd8dbd"

[[constraint]]
  name = "github.com/whyrusleeping/go-logging"
  revision = "0457bb6b88fc1973573aaf6b5145d8d3ae972390"

[[override]]
  name = "github.com/whyrusleeping/go-smux-multistream"
  version = "2.0.2"

[[override]]
  name = "github.com/shopspring/decimal"
  version = "1.1.0"

[[override]]
  name = "github.com/whyrusleeping/go-smux-yamux"
  revision = "eac25f3e2d47aae211e457e7664b52634c95eea8"

[[constraint]]
  name = "golang.org/x/crypto"
  revision = "0e37d006457bf46f9e6692014ba72ef82c33022c"

[[constraint]]
  name = "golang.org/x/net"
  revision = "26e67e76b6c3f6ce91f7c52def5af501b4e0f3a2"

[[constraint]]
  name = "gopkg.in/resty.v1"
  version = "1.9.1"

[[prune.project]]
    name = "github.com/libp2p/go-libp2p"
    unused-packages = false

[[prune.project]]
    name = "github.com/centrifuge/centrifuge-ethereum-contracts"
    unused-packages = false

[[prune.project]]
    name = "github.com/ethereum/go-ethereum"
    unused-packages = false

[[prune.project]]
    name = "github.com/centrifuge/centrifuge-protobufs"
    unused-packages = false

[[prune.project]]
    name = "github.com/hashicorp/go-multierror"
    unused-packages = false

[prune]
  go-tests = true
  unused-packages = true
[[constraint]]
  branch = "master"
  name = "github.com/savaki/jq"

[[constraint]]
  branch = "master"
  name = "github.com/gavv/httpexpect"

[[constraint]]
  branch = "master"
  name = "github.com/common-nighthawk/go-figure"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "4.0.2"

[[constraint]]
  name = "github.com/go-chi/render"
  version = "1.0.1"

[[constraint]]
  name = "github.com/swaggo/swag"
  version = "1.5.0"

[[prune.project]]
  name = "github.com/swaggo/swag"
  unused-packages = false

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"
