version: '3'
services:
  cent-api:
    image: "centrifugeio/go-centrifuge:20180926-6923e53"
    container_name: cent-api
    environment:
      - CENT_MODE
    command: ["${ADDITIONAL_CMD}"]
    ports:
      - "${API_PORT}:8082"
      - "${P2P_PORT}:38202"
    volumes:
      - ${API_DATADIR}:/root/.centrifuge/db
      - ${API_CONFIGDIR}:/root/.centrifuge/config