centrifugeNetwork: centrifugeRussianhillEthRinkeby
networks:
  # Local testing contract addresses need to be set with env variables.
  testing:
    id: 333
    ethereumNetworkId: 8383
    bootstrapPeers:
      - "/ip4/127.0.0.1/tcp/38202/ipfs/QmTQxbwkuZYYDfuzTbxEAReTNCLozyy558vQngVvPMjLYk"
      - "/ip4/127.0.0.1/tcp/38203/ipfs/QmVf6EN6mkqWejWKW2qPu16XpdG3kJo1T3mhahPB5Se5n1"
    contractAddresses:
      identityFactory: ""
      identityRegistry: ""
      anchorRegistry: ""
      anchorRepository: ""

  centrifugeRussianhillEthIntegration:
    id: 101
    ethereumNetworkId: 8383
    bootstrapPeers:
      - "/ip4/127.0.0.1/tcp/38202/ipfs/QmTQxbwkuZYYDfuzTbxEAReTNCLozyy558vQngVvPMjLYk"
      - "/ip4/127.0.0.1/tcp/38203/ipfs/QmVf6EN6mkqWejWKW2qPu16XpdG3kJo1T3mhahPB5Se5n1"
    contractAddresses:
      identityFactory: "0x73231b49306acb6ab074a07378f376fc9bdb2716"
      identityRegistry: "0xd68c607bbc2080006893140916a6821fd713b292"
      anchorRegistry: "0xb571fe40de2d61e954df9ca4e961f69488f135a0"

  centrifugeRussianhillEthRinkeby:
    id: 51
    bootstrapPeers:
      - "/ip4/127.0.0.1/tcp/38202/ipfs/QmTQxbwkuZYYDfuzTbxEAReTNCLozyy558vQngVvPMjLYk"
      - "/ip4/127.0.0.1/tcp/38203/ipfs/QmVf6EN6mkqWejWKW2qPu16XpdG3kJo1T3mhahPB5Se5n1"

    ethereumNetworkId: 4
    contractAddresses: 
      identityFactory: "0x90d294571e73842697a66b7a99a09dd6c73d356d"
      identityRegistry: "0x9660c039d311453af0d58c5666723d9c2fa7d6ec"
      anchorRegistry: "0x342a74b382d19da64988b376d0e4a656b7bfa5dd"
      anchorRepository: "0x7f854dfa98012d7fa55c803bba2260bcdee4b5ed"

queue:
  numWorkers: 2
  workerWaitTimeMS: 1

ethereum:
  defaultAccountName: "main"
  nodeURL: ws://localhost:9546
  gasPrice: 1000000000
  gasLimit: 4712388
  contextWaitTimeout: "600s"
  maxRetries: 200
  intervalRetry: "2s"
  txPoolAccessEnabled: true

